name: Update latest tag

on:
  push:
    branches:
      - main

jobs:
  update-latest-tag:
    runs-on: ubuntu-latest
    name: Update latest tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update latest tag
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git tag -f latest
          git push -f origin latest